### ISSUE TITLE
Blurry snaps and titles for Sega CD 

### ISSUE THREAD

**Issue by tjanas** [libretro-thumbnails/Sega_-_Mega-CD_-_Sega_CD#2]
These appear to have been captured with filters applied, and possibly in a non-native resolution. If there is interest, I can provide replacements.

**Comment by RobLoach** [comment]
Would be great to get some beautiful captures.

**Comment by tjanas** [comment]
I will work on this.

**Comment by tjanas** [comment]
> Would be great to get some beautiful captures.

@RobLoach Please review my [pull request](https://github.com/libretro-thumbnails/Sega_-_Mega-CD_-_Sega_CD/pull/3).

**Comment by RobLoach** [comment]
Thanks a lot for cleaning those up. They look much better!
